server {
    listen 80;
    server_name localhost;

    location /stub_status {
        stub_status on;
        access_log off;

        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.0.0.0/12;
        allow 192.168.0.0/16;
        deny all;
    }

    # 2. On liste explicitement les préfixes qui doivent aller au Backend
    location ~* ^/(auth|users|notifications) {
        proxy_pass http://backend-api:8080; # Pas de "/" à la fin pour garder l'URI exacte
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
    # --- config pour le sse ---
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Cache-Control "no-cache";
        chunked_transfer_encoding on;
    }

        # 1. Le Frontend Angular gère la racine par défaut
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cache Control pour les fichiers statiques du front
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff2)$ {
        root /usr/share/nginx/html;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";

    }
}