spring.config.import=optional:file:.env[.properties]
spring.application.name=API Security PoC

server.port=8080
management.server.port=8087
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always


spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true

jwt.secret =${JWT_SECRET}
jwt.expiration =3600000
refresh.expiration-days =7
security.cookie.domain=localhost
security.cookie.secure=false  
