
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG

jwt.secret=test-secret-key-just-for-integration-tests-12345
jwt.expiration=3600
