spring.application.name=API Security PoC

server.port=8080
management.server.port=8087
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.web.server.request.autotime.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=tmuser
spring.datasource.password=tmpass
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = mymostcomplexeandlongsecretforjwt
jwt.expiration = 3600000
refresh.expiration-days= 2
security.cookie.domain=localhost
security.cookie.secure=false  
