spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=tmuser
spring.datasource.password=tmpass
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = mymostcomplexeandlongsecretforjwt
jwt.expiration = 3600000
refresh.expiration-days= 2
security.cookie.domain=localhost
security.cookie.secure=false  
