/**
 * Access management PoC
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response object for user authentication
 */
export interface AuthResponse { 
    /**
     * Authentication token
     */
    accessToken: string;

}
