/**
 * Access management PoC
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object for user authentication
 */
export interface AuthRequest { 
    /**
     * Username of the user attempting to authenticate
     */
    username?: string;
    /**
     * Password of the user attempting to authenticate
     */
    password?: string;
}

