/**
 * Access management PoC
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RoleEnum, StatusEnum } from "./userRequest";


/**
 * Response DTO for user data
 */
export interface UserResponse { 
    /**
     * Unique identifier of the user
     */
    id?: number;
    /**
     * Username of the user
     */
    username?: string;
    /**
     * Email address of the user
     */
    email?: string;
    /**
     * Role assigned to the user
     */
    role?: RoleEnum;
    /**
     * Status of the user account
     */
    status?: StatusEnum;
    /**
     * Timestamp when the user was created
     */
    createdAt?: string;
    /**
     * Username who created this user
     */
    createdBy?: string;
    /**
     * Timestamp of last update
     */
    updatedAt?: string;
    /**
     * Username who last updated this user
     */
    updatedBy?: string;
}




