/**
 * Access management PoC
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request DTO for creating a user
 */
export interface UserRequest { 
    /**
     * Username of the user
     */
    username: string;
    /**
     * Password of the user
     */
    password: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Role assigned to the user
     */
    role: RoleEnum;
    /**
     * Status of the user account
     */
    status: StatusEnum;
}
export enum RoleEnum {
    Admin = 'ADMIN',
    User = 'USER'
};
export enum StatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
};

